### ISSUE TITLE
What is the font of the theme?

### ISSUE THREAD

**Issue by camiplata** [gbif/hp-colombian-biodiversity#19]
We ask this as want to use a similar font for the new arts for news and others.

**Comment by MortenHofft** [comment]
It is using whatever font is installed in your computer. So there is no single font. It depends on the computer you sit at. Below you see the font-family. It will choose whichever is the first font your computer have.

```
font-family: BlinkMacSystemFont, -apple-system, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", "Helvetica", "Arial", sans-serif;
```

But it is possible to define a single font. I can add how to in the documentation. I chose not to in the base theme and because I like not having the overhead of loading a font.

Specifying fonts can additionally be difficult on a site that can be translated to e.g. chinese as the font is unlikely to cover those characters, but that is less relevant for your site of course :)
